[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "whisk"
version = "0.1"
description = "A fun, mood-based programming language"
requires-python = ">=3.7"
authors = [
    {name = "Unnati", email = "chhabraunnati234@gmail.com"}
]
readme = "README.md"